/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formCadastro;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import view.TelaPrincipal;

/**
 *
 * @author Dell
 */
public class FormInterprete extends javax.swing.JDialog {

    TelaPrincipal t = new TelaPrincipal();
    
    public FormInterprete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Center the text
        txtNomeInter.setHorizontalAlignment(JTextField.CENTER);
        txtCodInter.setHorizontalAlignment(JTextField.CENTER);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadInt = new javax.swing.JLabel();
        jpanelMain = new javax.swing.JPanel();
        txtNomeInter = new javax.swing.JTextField();
        lblNomeInt = new javax.swing.JLabel();
        txtCodInter = new javax.swing.JTextField();
        lblCodInt = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        lblTipoInt = new javax.swing.JLabel();
        btnSalvarInt = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblCadInt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCadInt.setText("Cadastro de Interprete");

        jpanelMain.setBackground(new java.awt.Color(204, 204, 255));
        jpanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNomeInter.setToolTipText("Nome do Interprete");
        txtNomeInter.setName(""); // NOI18N
        txtNomeInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInterActionPerformed(evt);
            }
        });

        lblNomeInt.setText("Nome do Interprete");

        txtCodInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodInterActionPerformed(evt);
            }
        });

        lblCodInt.setText("Codigo do Interprete");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconhecido", "Tenor", "Orquestra", "Trio", "Quarteto", "Opera" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        lblTipoInt.setText("Tipo");

        javax.swing.GroupLayout jpanelMainLayout = new javax.swing.GroupLayout(jpanelMain);
        jpanelMain.setLayout(jpanelMainLayout);
        jpanelMainLayout.setHorizontalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblNomeInt))
                    .addGroup(jpanelMainLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addComponent(txtCodInter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomeInter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpanelMainLayout.createSequentialGroup()
                                .addComponent(lblCodInt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTipoInt)
                                .addGap(43, 43, 43)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jpanelMainLayout.setVerticalGroup(
            jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeInter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodInt)
                    .addComponent(lblTipoInt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodInter, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboTipo))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnSalvarInt.setText("Salvar");
        btnSalvarInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarIntActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarInt)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(134, 134, 134)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadInt)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarInt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodInterActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
    
      /*  jComboTipo.removeAllItems();
        for (int i = 1900; i <= 2011; i++) {
            jComboTipo.addItem(i+"");
        }
       */
    }//GEN-LAST:event_jComboTipoActionPerformed

    private void txtNomeInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInterActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        
        txtCodInter.setText("");
        txtNomeInter.setText("");
        jComboTipo.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarIntActionPerformed
        if(txtCodInter.getText().equals("") || txtNomeInter.getText().equals("")){

                        JOptionPane.showMessageDialog(null, "Preencha todos os campos");

        }else{
            try {
              PreparedStatement ps = t.conecta.con.prepareStatement("insert into INTERPRETE"
                      + "(CODIGO_INTERPRETE, NOME, TIPO)"+
                      " values(?,?,?)");
              ps.setInt(1, Integer.parseInt(txtCodInter.getText()));
              ps.setString(2, txtNomeInter.getText());
              ps.setString(3, (String) jComboTipo.getSelectedItem());
              ps.executeUpdate();
              JOptionPane.showMessageDialog(null, "Interprete cadastrado com sucesso");
              txtCodInter.setText("");
              txtNomeInter.setText("");
              jComboTipo.setSelectedIndex(0);
              dispose();
          } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, "Falha ao cadastrar Interprete\n"+ex.getMessage());
          }
      }
    }//GEN-LAST:event_btnSalvarIntActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInterprete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInterprete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInterprete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInterprete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormInterprete dialog = new FormInterprete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvarInt;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JPanel jpanelMain;
    private javax.swing.JLabel lblCadInt;
    private javax.swing.JLabel lblCodInt;
    private javax.swing.JLabel lblNomeInt;
    private javax.swing.JLabel lblTipoInt;
    private javax.swing.JTextField txtCodInter;
    private javax.swing.JTextField txtNomeInter;
    // End of variables declaration//GEN-END:variables
}
