/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formCadastro;

/**
 *
 * @author Dell
 */
public class FormFaixa extends javax.swing.JDialog {

    /**
     * Creates new form FormFaixa
     */
    public FormFaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtTempoExec.setHorizontalAlignment(txtTempoExec.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadFaixa = new javax.swing.JLabel();
        panelCadFaixa = new javax.swing.JPanel();
        lblNomeFaixa = new javax.swing.JLabel();
        txtNomeFaixa = new javax.swing.JTextField();
        lblNumFaixa = new javax.swing.JLabel();
        txtNumFaixa = new javax.swing.JFormattedTextField();
        lblTempExec = new javax.swing.JLabel();
        lblOBStempo = new javax.swing.JLabel();
        txtTempoExec = new javax.swing.JFormattedTextField();
        txtTipoGrav = new javax.swing.JLabel();
        btnAlbum = new javax.swing.JButton();
        btnTipoComp = new javax.swing.JButton();
        btnInterpretes = new javax.swing.JButton();
        btnCompositores = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelAlbumSelec = new javax.swing.JPanel();
        lblAlbumInPanel = new javax.swing.JLabel();
        lblAlbumSelected = new javax.swing.JLabel();
        panelTipoCompo = new javax.swing.JPanel();
        lblTipoCompPanel = new javax.swing.JLabel();
        lblTipoCompSelected = new javax.swing.JLabel();
        panelInterpretes = new javax.swing.JPanel();
        lblInterpretesPanel = new javax.swing.JLabel();
        lblInterpreteSelected = new javax.swing.JLabel();
        panelCompositores = new javax.swing.JPanel();
        lblCompositoresPanel = new javax.swing.JLabel();
        lblCompositoresSelected = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCadFaixa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCadFaixa.setText("Cadastro de Faixa");

        panelCadFaixa.setBackground(new java.awt.Color(204, 204, 240));
        panelCadFaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNomeFaixa.setText("Nome da Faixa");

        lblNumFaixa.setText("Número da Faixa");

        try {
            txtNumFaixa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFaixaActionPerformed(evt);
            }
        });

        lblTempExec.setText("Tempo de Execução");

        lblOBStempo.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lblOBStempo.setText("hh:mm:ss");

        try {
            txtTempoExec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtTipoGrav.setText("Tipo de Gravação");

        btnAlbum.setText("Álbum");

        btnTipoComp.setText("Tipo de Composição");

        btnInterpretes.setText("Interpretes");

        btnCompositores.setText("Compositores");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADD", "DDD" }));

        panelAlbumSelec.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAlbumInPanel.setText("Álbum");

        lblAlbumSelected.setText("Nenhum Álbum Selecionado");

        javax.swing.GroupLayout panelAlbumSelecLayout = new javax.swing.GroupLayout(panelAlbumSelec);
        panelAlbumSelec.setLayout(panelAlbumSelecLayout);
        panelAlbumSelecLayout.setHorizontalGroup(
            panelAlbumSelecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumSelecLayout.createSequentialGroup()
                .addGroup(panelAlbumSelecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlbumSelecLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAlbumSelected))
                    .addGroup(panelAlbumSelecLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblAlbumInPanel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlbumSelecLayout.setVerticalGroup(
            panelAlbumSelecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlbumSelecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlbumInPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlbumSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTipoCompo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTipoCompPanel.setText("Tipo de Composição");

        lblTipoCompSelected.setText("Nenhum Tipo de Composição Selecionado");

        javax.swing.GroupLayout panelTipoCompoLayout = new javax.swing.GroupLayout(panelTipoCompo);
        panelTipoCompo.setLayout(panelTipoCompoLayout);
        panelTipoCompoLayout.setHorizontalGroup(
            panelTipoCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCompoLayout.createSequentialGroup()
                .addGroup(panelTipoCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTipoCompoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTipoCompPanel))
                    .addGroup(panelTipoCompoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipoCompSelected)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTipoCompoLayout.setVerticalGroup(
            panelTipoCompoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoCompoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoCompPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoCompSelected)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelInterpretes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInterpretesPanel.setText("Interpretes");

        lblInterpreteSelected.setText("Nenhum Interprete Selecionado");
        lblInterpreteSelected.setAutoscrolls(true);

        javax.swing.GroupLayout panelInterpretesLayout = new javax.swing.GroupLayout(panelInterpretes);
        panelInterpretes.setLayout(panelInterpretesLayout);
        panelInterpretesLayout.setHorizontalGroup(
            panelInterpretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInterpretesLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelInterpretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInterpretesLayout.createSequentialGroup()
                        .addComponent(lblInterpreteSelected)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInterpretesLayout.createSequentialGroup()
                        .addComponent(lblInterpretesPanel)
                        .addGap(65, 65, 65))))
        );
        panelInterpretesLayout.setVerticalGroup(
            panelInterpretesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInterpretesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInterpretesPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInterpreteSelected)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panelCompositores.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCompositoresPanel.setText("Interpretes");

        lblCompositoresSelected.setText("Nenhum Compositor Selecionado");
        lblCompositoresSelected.setAutoscrolls(true);

        javax.swing.GroupLayout panelCompositoresLayout = new javax.swing.GroupLayout(panelCompositores);
        panelCompositores.setLayout(panelCompositoresLayout);
        panelCompositoresLayout.setHorizontalGroup(
            panelCompositoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompositoresLayout.createSequentialGroup()
                .addGroup(panelCompositoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompositoresLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblCompositoresSelected))
                    .addGroup(panelCompositoresLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblCompositoresPanel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCompositoresLayout.setVerticalGroup(
            panelCompositoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompositoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompositoresPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompositoresSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCadFaixaLayout = new javax.swing.GroupLayout(panelCadFaixa);
        panelCadFaixa.setLayout(panelCadFaixaLayout);
        panelCadFaixaLayout.setHorizontalGroup(
            panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadFaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadFaixaLayout.createSequentialGroup()
                        .addComponent(panelAlbumSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(panelCadFaixaLayout.createSequentialGroup()
                        .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCadFaixaLayout.createSequentialGroup()
                                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCadFaixaLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lblOBStempo))
                                    .addComponent(lblNomeFaixa)
                                    .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtTempoExec, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTempExec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(74, 74, 74))
                            .addComponent(txtNomeFaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCadFaixaLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelCadFaixaLayout.createSequentialGroup()
                        .addComponent(panelTipoCompo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadFaixaLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnTipoComp)
                            .addGap(47, 47, 47))
                        .addGroup(panelCadFaixaLayout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadFaixaLayout.createSequentialGroup()
                            .addComponent(txtTipoGrav)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNumFaixa)
                            .addContainerGap()))))
            .addGroup(panelCadFaixaLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnInterpretes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCompositores, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(panelCadFaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInterpretes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCompositores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCadFaixaLayout.setVerticalGroup(
            panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadFaixaLayout.createSequentialGroup()
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadFaixaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomeFaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempExec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOBStempo)
                        .addGap(4, 4, 4)
                        .addComponent(txtTempoExec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadFaixaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumFaixa)
                            .addComponent(txtTipoGrav))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTipoComp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTipoCompo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlbumSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInterpretes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompositores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInterpretes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCompositores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");

        btnLimpar.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCadFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(lblCadFaixa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadFaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCadFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormFaixa dialog = new FormFaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlbum;
    private javax.swing.JButton btnCompositores;
    private javax.swing.JButton btnInterpretes;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTipoComp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAlbumInPanel;
    private javax.swing.JLabel lblAlbumSelected;
    private javax.swing.JLabel lblCadFaixa;
    private javax.swing.JLabel lblCompositoresPanel;
    private javax.swing.JLabel lblCompositoresSelected;
    private javax.swing.JLabel lblInterpreteSelected;
    private javax.swing.JLabel lblInterpretesPanel;
    private javax.swing.JLabel lblNomeFaixa;
    private javax.swing.JLabel lblNumFaixa;
    private javax.swing.JLabel lblOBStempo;
    private javax.swing.JLabel lblTempExec;
    private javax.swing.JLabel lblTipoCompPanel;
    private javax.swing.JLabel lblTipoCompSelected;
    private javax.swing.JPanel panelAlbumSelec;
    private javax.swing.JPanel panelCadFaixa;
    private javax.swing.JPanel panelCompositores;
    private javax.swing.JPanel panelInterpretes;
    private javax.swing.JPanel panelTipoCompo;
    private javax.swing.JTextField txtNomeFaixa;
    private javax.swing.JFormattedTextField txtNumFaixa;
    private javax.swing.JFormattedTextField txtTempoExec;
    private javax.swing.JLabel txtTipoGrav;
    // End of variables declaration//GEN-END:variables
}
